CREATE TABLE FUNDAMENTAL_DATA_NOTIFICATIONS (
  TRANSACTION_ID NUMBER(20,0),
  INFORMATION_TYPE_ID VARCHAR (10),
  OPERATION_TYPE NUMBER(20,-1),
  CONTRIBUTION_ITEM NVARCHAR2(1000),
  NOTIFICATION_ID NUMBER (28,0),
  PRIMARY KEY (NOTIFICATION_ID)
)